feat: Update pr check.yml

diff --git a/.github/workflows/pr check.yml b/.github/workflows/pr check.yml
--- a/.github/workflows/pr check.yml
+++ b/.github/workflows/pr check.yml
@@ -37,39 +37,65 @@ jobs:
           echo ${{github.event.pull_request.number}} 
           echo ${{github.event.number}}
           echo npm ${{ steps.npm-version.outputs.current-version }}
+          
       - name: Log all commits
         run: |
           echo "Logging all commits between latest tag and current branch head"
           git log ${{ steps.git-tag-latest.outputs.tag }}..HEAD --oneline
-          
-      - name: Check if tag already exists
+
+      - name: Get release commit message
+        id: release-commit
         run: |
+          RELEASE_COMMIT_MESSAGE=$(git log --grep="Release-As: " -1 --pretty=format:"%s")
+          echo "RELEASE_COMMIT_MESSAGE=$RELEASE_COMMIT_MESSAGE" >> $GITHUB_ENV
+
+      - name: Check if release commit is as expected
+        run: |
+          echo "Last release commit message: ${{ env.RELEASE_COMMIT_MESSAGE }}"
           if [[ "${{ env.GIT_VERSION }}" == "${{ steps.npm-version.outputs.current-version }}" ]]; then
             echo "Versions match. Skipping publish."
           else
             echo "Versions do not match. Checking if tag exists."
             tag_exists=$(git tag -l "v${{ steps.npm-version.outputs.current-version }}")
             if [[ -n "$tag_exists" ]]; then
-              echo git tag for npm versions already exists.
+              echo "Git tag for npm version already exists."
               exit 1
             else
-              echo "push_commit=true" >> $GITHUB_ENV
-              echo "Tag does not exist. Checking for release commit."
-              release_commit=$(git log --grep="Release-As: ${{ steps.npm-version.outputs.current-version }}" -1)
-              if [[ -z "$release_commit" ]]; then
-                echo "Release commit not found. Please run the following command:"
-                echo 'git commit --allow-empty -m "chore: release ${{ steps.npm-version.outputs.current-version }}" -m "Release-As: ${{ steps.npm-version.outputs.current-version }}"'
-                exit 1
-              else
-                echo "Release commit found. Proceeding with the workflow."
+              echo "Tag does not exist. Checking release commit message."
+              if [[ "${{ env.RELEASE_COMMIT_MESSAGE }}" != *"chore: release ${{ steps.npm-version.outputs.current-version }}"* ]]; then
+                echo "push_commit=true" >> $GITHUB_ENV
               fi
-
-              # git config --global user.name 'github-actions[bot]'
-              # git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-              # git commit --allow-empty -m "chore: release ${{ steps.npm-version.outputs.current-version }}" -m "Release-As: ${{ steps.npm-version.outputs.current-version }}"
-              # # git push
             fi        
           fi
+          
+      # - name: Check if tag already exists
+      #   run: |
+      #     if [[ "${{ env.GIT_VERSION }}" == "${{ steps.npm-version.outputs.current-version }}" ]]; then
+      #       echo "Versions match. Skipping publish."
+      #     else
+      #       echo "Versions do not match. Checking if tag exists."
+      #       tag_exists=$(git tag -l "v${{ steps.npm-version.outputs.current-version }}")
+      #       if [[ -n "$tag_exists" ]]; then
+      #         echo git tag for npm versions already exists.
+      #         exit 1
+      #       else
+      #         echo "push_commit=true" >> $GITHUB_ENV
+      #         echo "Tag does not exist. Checking for release commit."
+      #         release_commit=$(git log --grep="Release-As: ${{ steps.npm-version.outputs.current-version }}" -1)
+      #         if [[ -z "$release_commit" ]]; then
+      #           echo "Release commit not found. Please run the following command:"
+      #           echo 'git commit --allow-empty -m "chore: release ${{ steps.npm-version.outputs.current-version }}" -m "Release-As: ${{ steps.npm-version.outputs.current-version }}"'
+      #           exit 1
+      #         else
+      #           echo "Release commit found. Proceeding with the workflow."
+      #         fi
+
+      #         # git config --global user.name 'github-actions[bot]'
+      #         # git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+      #         # git commit --allow-empty -m "chore: release ${{ steps.npm-version.outputs.current-version }}" -m "Release-As: ${{ steps.npm-version.outputs.current-version }}"
+      #         # # git push
+      #       fi        
+      #     fi
 
       # - name: Checkout PR
       #   if: ${{env.push_commit == 'true'}} 
